spring.application.name=Raqaf

# ===== PostgreSQL Database =====
# Local Postgres example:
#   spring.datasource.url=jdbc:postgresql://localhost:5432/ecommercedb
# Neon (cloud) example:
#   spring.datasource.url=jdbc:postgresql://<your-neon-host>/<dbname>?sslmode=require
spring.datasource.url=jdbc:postgresql://ep-curly-tree-at3to2v9.c-9.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=neondb_owner
spring.datasource.password=npg_XnG8acNr2SfO

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.tomcat.threads.max=20
server.tomcat.threads.min-spare=2

# ===== Logging =====
logging.level.com.example.ecommerce=DEBUG
logging.level.org.springframework.security=DEBUG

# ===== Swagger / OpenAPI docs =====
# Once running, visit http://localhost:8080/swagger-ui.html
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
JWT_SECRET=6684071f5c11cae72dd20f2983933531d9d51a567f0c0c183256989260ed1cf2